### ISSUE TITLE
Terraform creation of all AWS resources

### ISSUE THREAD

**Issue by leewallen** [linc-lion/linc-cv#1]
Terraform creation of all AWS resources.

- [x] IAM users, roles, policies
    - [x] Role for deploying EC2 instance
- [x] EC2 Instances
    - [x] Launch using AMI
    - [ ] (Optional) Launch using launch template
- [x] S3 bucket for terraform state
- [x] Identify any resources not identified yet
- [x] Document S3 buckets that already exist - some buckets look to be unused

**Comment by shihgianlee** [comment]
See PR https://github.com/linc-lion/linc-cv/pull/10
